### ISSUE TITLE
Not working on Xcode 10

### ISSUE THREAD

**Issue by aveiga** [backslash-f/carthage-playground#1]
Hi,

first, thank you very much for this project!

Now, this doesn't seem to be working on Xcode 10. I tried following the steps on the SO thread that originated this project and the same happens: build succeeds (although very, very fast) but the playground is still unable to load the Charts library.

Thanks in advance for any help 👍🏻

**Comment by flockoffiles** [comment]
Just add the following line to copy-frameworks.sh before the cp command:
mkdir -p "$DEBUG_DIR"

(Apparently, Xcode10 does not create the build products folder)

**Comment by backslash-f** [comment]
Thanks @darrarski! Nice catch.
@aveiga I incorporated most of the changes done by @darrarski into this repo.
Things should be working now. 👍

**Comment by backslash-f** [comment]
(I didn't notice there was a PR opened for it, so I just reverted my changes and merged @darrarski PR).
